In [3]:
import numpy as np
import pandas as pd
import scipy.linalg as sc
import matplotlib.pyplot as plt

5.1. Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B. Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.

-5E



5.2. Вычислите определитель:
[[1, 2, 3],
[4, 0, 6],
[7, 8, 9]]


In [4]:
A = [[1, 2, 3], [4, 0, 6], [7, 8, 9]]
detA = np.linalg.det(A)
round(detA, 2)

60.0

5.3.
    Вычислите матрицу, обратную данной:
    [[1, 2, 3],
    [4, 0, 6],
    [7, 8, 9]]

In [6]:
A1 = np.linalg.inv(A)
A1

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

Приведите пример матрицы 4х4, ранг которой равен 1.



In [25]:
B = [[1, 2, 4, 8], [4, 8, 16, 32], [7,14, 28,  56]]
np.linalg.matrix_rank(B)

1



5.4. Вычислите скалярное произведение двух векторов:
(1, 5) и (2, 8)


In [14]:
a = [1, 5]
b = [2, 8]
c = np.dot(a, b)
c

42

5.5 Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3)

In [15]:
a = [1, 5, 0]
b = [2, 8, 7]
c = [7, 1.5, 3]
d = np.dot(a, np.cross(b, c))
d

228.5

# Решите линейную систему



In [17]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

In [18]:
detA = np.linalg.det(A)
detA

59.999999999999986

In [20]:
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])


# Найдите псевдорешение:
    x + 2y – z = 1
    3x – 4y = 7
    8x – 5y + 2z = 12
    2x – 5z = 7
    11x +4y – 7z = 15



In [28]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([[1, 7, 12, 7, 15]])

In [29]:
np.linalg.matrix_rank(A)

3

In [30]:
C = np.concatenate((A, B.T), axis=1)
np.linalg.matrix_rank(C)

4

In [32]:
np.linalg.lstsq(A, B.T,rcond=None)

(array([[ 1.13919353],
        [-0.90498444],
        [-0.9009803 ]]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

# Сколько решений имеет линейная система:

In [34]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([12, 2, 1])

In [35]:
np.linalg.matrix_rank(A)


2

Система имеет бесконечно много решений 

# Вычислите LU-разложение матрицы:

In [38]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])

In [39]:
P, L, U = sc.lu(A)

print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [40]:
B = np.array([14, 14, 14])
np.linalg.solve(A, B)

array([16.59259259, -0.51851852, -0.51851852])

# Найдите нормальное псевдорешение недоопределенной системы: x + 2y – z = 1 8x – 5y + 2z = 12 Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум.



In [42]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([[1, 12]])


In [44]:
np.linalg.lstsq(A, B.T,rcond=None)

(array([[ 1.38191882],
        [-0.18081181],
        [ 0.0202952 ]]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

# Найдите одно из псевдорешений вырожденной системы:


In [49]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 5, 11]])

In [50]:
np.linalg.matrix_rank(A)

2

In [51]:
C = np.concatenate((A, B.T), axis=1)
np.linalg.matrix_rank(C)

3

In [53]:
np.linalg.lstsq(A, B.T,rcond=None)


(array([[ 1.25],
        [ 0.5 ],
        [-0.25]]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))